### ISSUE TITLE
java.lang.OutOfMemoryError:Java heap space

### ISSUE THREAD

**Issue by lileixing** [opensourceBIM/IfcOpenShell-BIMserver-plugin#11]
I have an ifc file that is 300M in size.

- void write_contents(LittleEndianDataOutputStream s) throws IOException {
- 			if (length == -1) {
- 				// This is now the point where memory problems will arise for large models
- 				ByteArrayOutputStream baos = new ByteArrayOutputStream();
- 				IOUtils.copy(ifcInputStream, baos);
-                                 // crash here 
- 				writeStringBinary(s, baos.toByteArray());
- 			} else {
- 				writeStringBinary(s, ifcInputStream, (int) length);
- 			}
- 		}

**Comment by rubendel** [comment]
Please put effort into formatting your issue. The solution for for `java.lang.OutOfMemoryError` is to allocate more memory to your JVM.
