### ISSUE TITLE
ifcopenshell problem

### ISSUE THREAD

**Issue by sungatetop** [opensourceBIM/IfcOpenShell-BIMserver-plugin#13]
Hello , when BIMServer  installed plugin ifcopenshellplugin ,it has this problem, 
> Installing ifcopenshellplugin...

		Method org/ifcopenshell/IfcOpenShellEnginePlugin.init(Lorg/bimserver/plugins/PluginContext;)V is abstract

		Setup aborted

> 
How could I fixed it？

**Comment by rubendel** [comment]
Versions please

**Comment by sungatetop** [comment]
BIMServer 1.5.51 with IfcOpenShell-BIMserver-plugin-ifcopenshellplugin-0.5.62

**Comment by rubendel** [comment]
Uhm that BIMserver version is from Fri Jul 01 07:43:19 UTC 2016, no way that's going to work with the latest version of the IOS plugin
