### ISSUE TITLE
convert to svg

### ISSUE THREAD

**Issue by oliviersaintgobain** [opensourceBIM/IfcOpenShell-BIMserver-plugin#2]
hello,
I saw in the IfcOpenShell blog that this module is able to convert ifc to SVG (2D plan).
this module is installed in my 1.5.63 BIMServer instance.
my questions are :
- does this module is able to convert from bimserver ?
- if yes, how to run it from a model checked in ?

thanks

**Comment by rubendel** [comment]
The BIMserver plugin of IfcOpenShell only generates 3D geometry at the moment.

**Comment by oliviersaintgobain** [comment]
thanks Ruben. Do you have a plan to generate 2D from 3D model ?

**Comment by rubendel** [comment]
No plans
