### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by epeter-** [opensourceBIM/IfcOpenShell-BIMserver-plugin#5]
tried to install ifcopenshell plugin

no executable found for the linux platorm

platorm is no typo it is the original massage when trying to install from bimvie

platform = debian9  with tomcat9.06
all other plugins install.
bimserver up and running

**Comment by arlem03** [comment]
Same issue with me. ifcopenshell won't install on BIMserver version 1.5.147 using BIMviews. I get a different error though: "Java.net.UnknownHostException:s3.amazonaws.com: Name or service not known."

**Comment by rubendel** [comment]
Pretty sure that has nothing to do with either BIMserver or IfcOpenShell. Yesterday there were some routing issues on the internet, so I guess it was just that.
