### ISSUE TITLE
not match IfcOpenShell version

### ISSUE THREAD

**Issue by renweiguo** [opensourceBIM/IfcOpenShell-BIMserver-plugin#7]
Hi,  I run bimserver with bimserverjar-1.5.117.jar, there are some errors in Bimserver.log, and 3D is not rendered.   The error is:

`org.bimserver.plugins.renderengine.RenderEngineException: Version mismatch: Plugin version IfcOpenShell-0.6.0a1-0 does not match IfcOpenShell version IfcOpenShell-0.5.0-dev-2`

This file "/tmp/org.opensourcebim.ifcopenshellplugin/IfcGeomServer-v0.6.0-e3b415a-macos64"  is downloaded by "org.opensourcebim.ifcopenshellplugin-0.5.38.jar", According IfcOpenShell code in IfcGeomServerClient.java,  I test it in my MaxOS shell command line, it return "?IfcOpenShell-0.5.0-dev-2".

How can I make it works? 
Thanks!

**Comment by rubendel** [comment]
I think there might be a problem with the OSX builds lagging behind. @aothms Any idea?

**Comment by aothms** [comment]
I am not near a OSX machine now so I cannot test. @renweiguo is this the case with other releases as well? e.g. https://s3.amazonaws.com/ifcopenshell-builds/IfcGeomServer-master-a0f37cf-macos64.zip

**Comment by aothms** [comment]
There are new builds online that address this problem: https://s3.amazonaws.com/ifcopenshell-builds/IfcGeomServer-v0.6.0-4380e1d-macos64.zip

They are under a different commit hash, so until the plugin code is updated to reference the new commit, you'll have to manually download and extract into the correct location.

Thanks for reporting this.

**Comment by renweiguo** [comment]
Thanks for your work!
